# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180622_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='邮箱的激活状态'),
        ),
    ]
